version: "3.9"
services:

    nginx:
        container_name: "${APP_TITLE}"
        ports:
            - "${APP_PORT}:80"
        build: ./dockerfiles/nginx
        links:
            - php
        volumes:
            - ./:/usr/share/nginx/www

    php:
        container_name: "${APP_NAME}"
        build: ./dockerfiles/php
        volumes:
            - ./:/usr/share/nginx/www

    mariadb:
        container_name: "${MARIADB_CONTAINER_NAME}"
        hostname: "${MARIADB_HOSTNAME}"
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "password"
        volumes:
            - ./storage/mariadb:/var/lib/mariadb
        ports:
            - 3306:3306

    redis:
        image: redis
        container_name: "${REDIS_CONTAINER_NAME}"
        hostname: "${REDIS_HOSTNAME}"
        restart: always
        volumes:
            - ./storage/redis:/data
        ports:
            - 6379:6379

networks:
    default:
        external: true
        name: 'os'
